/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hsvranger;

import java.awt.Window;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.core.Scalar;
import org.opencv.core.Size;
import org.opencv.highgui.Highgui;
import org.opencv.highgui.VideoCapture;
import org.opencv.imgproc.Imgproc;

/**
 *
 * @author Pranay
 */
public class MainJframe extends javax.swing.JFrame {

    int hmin, hmax=180, smin, smax=255, vmin, vmax=255;
    Mat source = new Mat(), hsv = new Mat();
    private ImageIcon imageico;
    MatOfByte matOfByte = new MatOfByte();
    VideoCapture capture;

    /**
     * Creates new form MainJframe
     */
    public MainJframe() throws InterruptedException {
        initComponents();
        this.setVisible(true);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hmaxSlider = new javax.swing.JSlider();
        vminSlider1 = new javax.swing.JSlider();
        smaxLable1 = new javax.swing.JLabel();
        hminLable1 = new javax.swing.JLabel();
        smintextfield = new javax.swing.JTextField();
        hmaxtextfild = new javax.swing.JTextField();
        smaxSlider = new javax.swing.JSlider();
        hmaxLable2 = new javax.swing.JLabel();
        hminLable2 = new javax.swing.JLabel();
        sminSlider1 = new javax.swing.JSlider();
        hmintextfield1 = new javax.swing.JTextField();
        smaxTextfield = new javax.swing.JTextField();
        vminLable3 = new javax.swing.JLabel();
        hminSlider1 = new javax.swing.JSlider();
        vmaxTextfield2 = new javax.swing.JTextField();
        vmaxLable4 = new javax.swing.JLabel();
        vmaxSlider2 = new javax.swing.JSlider();
        vmintextfield3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hmaxSlider.setMaximum(180);
        hmaxSlider.setValue(180);
        hmaxSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hmaxSliderStateChanged(evt);
            }
        });

        vminSlider1.setMaximum(255);
        vminSlider1.setValue(0);
        vminSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vminSlider1StateChanged(evt);
            }
        });

        smaxLable1.setText("S Max");

        hminLable1.setText("S min");

        smintextfield.setText("00");
        smintextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smintextfieldActionPerformed(evt);
            }
        });

        hmaxtextfild.setText("180");
        hmaxtextfild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmaxtextfildActionPerformed(evt);
            }
        });

        smaxSlider.setMaximum(255);
        smaxSlider.setValue(255);
        smaxSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                smaxSliderStateChanged(evt);
            }
        });

        hmaxLable2.setText("H Max");

        hminLable2.setText("H Min");

        sminSlider1.setMaximum(255);
        sminSlider1.setValue(0);
        sminSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sminSlider1StateChanged(evt);
            }
        });

        hmintextfield1.setText("00");

        smaxTextfield.setText("255");

        vminLable3.setText("V Min");

        hminSlider1.setMaximum(180);
        hminSlider1.setValue(0);
        hminSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hminSlider1StateChanged(evt);
            }
        });

        vmaxTextfield2.setText("255");
        vmaxTextfield2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vmaxTextfield2ActionPerformed(evt);
            }
        });

        vmaxLable4.setText("V Max");

        vmaxSlider2.setMaximum(255);
        vmaxSlider2.setValue(255);
        vmaxSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                vmaxSlider2StateChanged(evt);
            }
        });

        vmintextfield3.setText("00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(vmaxLable4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vmaxSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vmaxTextfield2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vminLable3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vminSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vmintextfield3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hminLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hminSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hmaxLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hmaxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hmintextfield1)
                            .addComponent(hmaxtextfild, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hminLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sminSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smintextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(smaxLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(smaxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(smaxTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hminLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(hminSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(hmintextfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hminLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(sminSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(smintextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(smaxSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(hmaxtextfild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(hmaxLable2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(hmaxSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(smaxLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(smaxTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vminSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vminLable3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(vmintextfield3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(vmaxSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vmaxLable4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(vmaxTextfield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smintextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smintextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_smintextfieldActionPerformed

    private void vmaxTextfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vmaxTextfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vmaxTextfield2ActionPerformed

    private void hmaxtextfildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmaxtextfildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hmaxtextfildActionPerformed

    private void hminSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hminSlider1StateChanged
        // TODO add your handling code here:
        hmin = hminSlider1.getValue(); 
        hmintextfield1.setText("" + hmin);  


    }//GEN-LAST:event_hminSlider1StateChanged

    private void hmaxSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hmaxSliderStateChanged

        // TODO add your handling code here:

        hmax = hmaxSlider.getValue();
        hmaxtextfild.setText("" + hmax);
    }//GEN-LAST:event_hmaxSliderStateChanged

    private void vminSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vminSlider1StateChanged
        // TODO add your handling code here:
        vmin = vminSlider1.getValue();
        vmintextfield3.setText("" + vmin);
    }//GEN-LAST:event_vminSlider1StateChanged

    private void vmaxSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_vmaxSlider2StateChanged
        // TODO add your handling code here:
        vmax = vmaxSlider2.getValue();
        vmaxTextfield2.setText("" + vmax);
    }//GEN-LAST:event_vmaxSlider2StateChanged

    private void sminSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sminSlider1StateChanged

        smin = sminSlider1.getValue();
        smintextfield.setText("" + smin);
        // TODO add your handling code here:
    }//GEN-LAST:event_sminSlider1StateChanged

    private void smaxSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_smaxSliderStateChanged
        // TODO add your handling code here:

        smax = smaxSlider.getValue();
        smaxTextfield.setText("" + smax);
    }//GEN-LAST:event_smaxSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        /* Create and display the form */
        MainJframe jframe = new MainJframe();
        jframe.performLogic();


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hmaxLable2;
    private javax.swing.JSlider hmaxSlider;
    private javax.swing.JTextField hmaxtextfild;
    private javax.swing.JLabel hminLable1;
    private javax.swing.JLabel hminLable2;
    private javax.swing.JSlider hminSlider1;
    private javax.swing.JTextField hmintextfield1;
    private javax.swing.JLabel smaxLable1;
    private javax.swing.JSlider smaxSlider;
    private javax.swing.JTextField smaxTextfield;
    private javax.swing.JSlider sminSlider1;
    private javax.swing.JTextField smintextfield;
    private javax.swing.JLabel vmaxLable4;
    private javax.swing.JSlider vmaxSlider2;
    private javax.swing.JTextField vmaxTextfield2;
    private javax.swing.JLabel vminLable3;
    private javax.swing.JSlider vminSlider1;
    private javax.swing.JTextField vmintextfield3;
    // End of variables declaration//GEN-END:variables

    private void performLogic() {
        VideoCapture capture = new VideoCapture(0);
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainJframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        capture.grab();
        Imshow i = new Imshow("Hello");
        while (true) {
            capture.read(source);
            Imgproc.cvtColor(source, source, Imgproc.COLOR_BGR2HSV_FULL);
            Scalar hsvMin = new Scalar(hmin, smin, vmin);
            Scalar hsvMax = new Scalar(hmax, smax, vmax);
            Core.inRange(source, hsvMin, hsvMax, hsv);
            Imgproc.GaussianBlur(hsv, hsv, new Size(5,5), 0);
            Core.flip(hsv, hsv, +1);
            
//            Imgproc.erode(hsv, hsv, Imgproc.getStructuringElement(Imgproc.MORPH_RECT, new Size(2, 2)));
//
//            Imgproc.dilate(hsv, hsv, Imgproc.getStructuringElement(Imgproc.MORPH_RECT, new Size(2, 2)));

        System.out.println(hsvMin);
        System.out.println(hsvMax);

            i.showImage(hsv);

        }
    }
}
